CREATE TABLE `cad_usuario` (
  `username` varchar(20) NOT NULL default '' COMMENT 'nick name do usuário\n',
  `senha` tinytext NOT NULL COMMENT 'Password do usuário',
  `Nome` varchar(40) NOT NULL default '' COMMENT 'Nome completo do usuário',
  `Endereco` varchar(40) default NULL COMMENT 'Endereço residencial',
  `Numero` int(5) default NULL COMMENT 'Número da residência',
  `Cidade` varchar(40) default NULL COMMENT 'Cidade',
  `Estado` char(2) default NULL COMMENT 'Estado',
  `Cep` int(8) default NULL COMMENT 'Cep residencial',
  `DDD` int(6) default NULL COMMENT 'DDD',
  `Fone` int(10) default NULL COMMENT 'Fone de contato',
  `DDDCel` int(6) default NULL COMMENT 'DDD do Celular',
  `Celular` int(10) default NULL COMMENT 'Número do Celular',
  `EMail` varchar(90) NOT NULL default '' COMMENT 'E-mail',
  `DataNasc` date default NULL COMMENT 'Data de Nascimento',
  `Time` int(8) unsigned default NULL COMMENT 'Time que torce',
  `Nivel` int(8) NOT NULL default '0' COMMENT 'Nivel 1=usuário normal 999999=administrador',
  `userid` int(8) NOT NULL auto_increment COMMENT 'Código do usuário',
  `flpublica` char(1) NOT NULL default 'S' COMMENT '"S" = publica dados   "N" = Não publica',
  `flconfirma` char(1) NOT NULL default 'N' COMMENT '"S" = Cadastro confirmado "N" = Não Confirmado',
  `dtcadastro` datetime default NULL COMMENT 'Data de cadastramento',
  PRIMARY KEY  (`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='cadastro de usuários do bolão'